<?php

/**
 * @file
 */

// Making the Devtrac frontpage an app.

/**
 * Implements hook_apps_app_info()
 */
function devtrac_frontpage_sitereports_apps_app_info() {
  return array(
    'configure form' => 'devtrac_frontpage_sitereports_app_configure_form',
  );
}

/**
 * implements hook_app_configure_form
 */
function devtrac_frontpage_sitereports_app_configure_form() {
  $form['devtrac_frontpage_sitereports_slogan'] = array(
    '#type' => 'textfield',
    '#title' => t('Slogan'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_slogan', 'Our mission is to show how world aid resources are distributed among supported in underdeveloped regions in the world'),
    '#required' => TRUE,
    '#description' => t('The slogan you want to have featured on your custom sitereports based front page.'),
  );

  // Add a custom submit handler.
  $form['#submit'][] = 'devtrac_frontpage_sitereports_app_configure_form_submit';

  return system_settings_form($form);
}

/**
 * Implements hook_app_configure_form_submit.
 * 
 * - Resets the site_frontpage variable.
 */
function devtrac_frontpage_sitereports_app_configure_form_submit($form, &$form_state) {
  // Reset the site_frontpage variable to 'frontpage-sitereports'.
  variable_set('site_frontpage', 'frontpage-sitereports');
  // Clear all caches for the view to be available and the title change to take effect.
  drupal_flush_all_caches();
}

/**
 * Implements hook_views_default_views_alter().
 * 
 * Saves the provided slogan into the views display page title so it will show
 * on the homepage instead of the default.
 * 
 * @param type $views
 *   The keyed array of views by reference.
 */
function devtrac_frontpage_sitereports_views_default_views_alter(&$views) {
  if (isset($views['devtrac_frontpage_sitereports'])) {
    // Retrieve the slogan from the variables.
    $slogan = variable_get('devtrac_frontpage_sitereports_slogan', 'Our mission is to show how world aid resources are distributed among supported in underdeveloped regions in the world');
    // Change the title of the views display graphpage title.
    $views['devtrac_frontpage_sitereports']->display['graphpage']->display_options['title'] = $slogan;
  }
}
