<?php

/**
 * @file
 */

// Making the Devtrac frontpage an app.

/**
 * Implements hook_apps_app_info()
 */
function devtrac_frontpage_sitereports_apps_app_info() {
  return array(
    'configure form' => 'devtrac_frontpage_sitereports_app_configure_form',
  );
}

/**
 * implements hook_app_configure_form
 */
function devtrac_frontpage_sitereports_app_configure_form() {
  $form['devtrac_frontpage_sitereports_slogan'] = array(
    '#type' => 'textfield',
    '#title' => t('Slogan'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_slogan', 'Our mission is to show how world aid resources are distributed among supported in underdeveloped regions in the world'),
    '#required' => TRUE,
    '#description' => t('The slogan you want to have featured on your custom sitereports based front page.'),
  );
  $form['devtrac_frontpage_sitereports_organisation_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Organisation'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_organisation_name', 'Organisation Name'),
    '#required' => TRUE,
    '#description' => t('The name of your organisation that will be featured on your custom sitereports based front page.'),
  );
  // Use the #managed_file FAPI element to upload a file.
  $form['devtrac_frontpage_sitereports_organisation_logo'] = array(
    '#type' => 'managed_file',
    '#title' => t('Logo'),
    '#description' => t('The logo of your organisation that will be featured on your custom sitereports based front page. Only files with extension gif, jpeg, jpg or png are allowed.'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_organisation_logo', ''),
    '#upload_validators' => array(
      'file_validate_extensions' => array('gif jpeg jpg png'),
    ),
    '#upload_location' => 'public://',
    '#process' => array('devtrac_frontpage_sitereports_file_element_process')
  );
  $form['devtrac_frontpage_sitereports_org_logo_alt_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Logo Alternative Text'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_org_logo_alt_text', ''),
    '#required' => TRUE,
    '#description' => t('The alternative text to put in place of the organisation logo if that is not available.'),
  );
  $form['devtrac_frontpage_sitereports_organisation_desc'] = array(
    '#type' => 'textarea',
    '#rows' => 5,
    '#title' => t('Description'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_organisation_desc', 'Organisation description.'),
    '#required' => TRUE,
    '#description' => t('A short description of your organisation that will be featured on your custom sitereports based front page.'),
  );
  $form['devtrac_frontpage_sitereports_about_us'] = array(
    '#type' => 'textarea',
    '#rows' => 5,
    '#title' => t('About Us'),
    '#default_value' => variable_get('devtrac_frontpage_sitereports_about_us', 'About us.'),
    '#required' => TRUE,
    '#description' => t('A short About Us of the people in your organisation that will be featured on your custom sitereports based front page.'),
  );

  // Add a custom submit handler.
  $form['#submit'][] = 'devtrac_frontpage_sitereports_app_configure_form_submit';

  return system_settings_form($form);
}

/**
 * Implements process callback defined earlier.
 */
function devtrac_frontpage_sitereports_file_element_process($element, &$form_state, $form) {
  $element = file_managed_file_process($element, $form_state, $form);
  return $element;
}
/**
 * Implements hook_app_configure_form_submit.
 * 
 * - Creates an Organisation and an About Us page to be placed
 *   on the front page using nodesinblock.
 * - Resets the site_frontpage variable.
 */
function devtrac_frontpage_sitereports_app_configure_form_submit($form, &$form_state) {
  // Get the data from the submitted form.
  $values = $form_state['values'];
  $organisation = $values['devtrac_frontpage_sitereports_organisation_name'];
  $logo = $values['devtrac_frontpage_sitereports_organisation_logo'];
    // Load the file.
  $file = file_load($logo);
  // Change status to permanent.
//  $file->status = FILE_STATUS_PERMANENT;
  // Save.
  if (file_save($file)) {
    drupal_set_message(t('The file has been uploaded.'));
  }
  else {
    drupal_set_message(t('The file could not be uploaded. Please contact the site administrator.'), 'error');
  }
  $logo_alt_text = $values['devtrac_frontpage_sitereports_org_logo_alt_text'];
  // Let's put the alt_text on the file object.
  $file->alt = $logo_alt_text;
  // While at it, also default the file title field to the alt_text.
  $file->title = $logo_alt_text;
  $description = $values['devtrac_frontpage_sitereports_organisation_desc'];
  $about_us = $values['devtrac_frontpage_sitereports_about_us'];

  // Do something with the $file object.
  $file_path = $file->uri;

  $results = db_select('nodesinblock', 'nib')
    ->fields('nib', array('nid', 'delta'))
    ->execute()
    ->fetchAll();
  if ($results) {
    foreach ($results as $result) {
      $node = node_load($result->nid);
      if ($result->delta == 0) {
        $node->body[$node->language][0]['value'] = $about_us;
        $node->body[$node->language][0]['summary'] = $about_us;
      }
      else {
        $node->title = $organisation;
        $node->field_image[$node->language][0] = (array) $file;
        $node->body[$node->language][0]['value'] = $description;
        $node->body[$node->language][0]['summary'] = $description;
      }
      // Only update the node. No need to update the nodesinblock information.
      node_save($node);
      // Clean up.
      unset($node);
    }
  }
  else {
    // Create a frontpage About Us page.
    // First create a new node object.
    $node = new stdClass();
    // Set the bundle type.
    $node->type = 'page';
    // Set the title.
    $node->title = t('About Us');
    // Set the language.
    $node->language = LANGUAGE_NONE;
     // Set the node path.
    $node->path = array('alias' => 'content/about-us');
    // Set some default values.
    node_object_prepare($node);
    // Set the author/owner of the node.
    $node->uid = 1;
    // Let's add standard body field
    $node->body[$node->language][0]['value'] = $about_us;
    $node->body[$node->language][0]['summary'] = $about_us;
    // Define the default plain_text format for the body field.
    $node->body[$node->language][0]['format'] = 'plain_text';
    // Prepare node for a submit.
    $node = node_submit($node);
    // Add nodesinblock settings to the node.
    $node->nodesinblock_delta = 0;
    $node->nodesinblock_weight = 0;
    $node->nodesinblock_visibility = '*';
    $node->nodesinblock_render = 'teaser:1';
    // Finaly, make sure that the nodesinblock implementation of
    // hook_node_insert() is fired.
    $node->nodesinblock_enable = TRUE;
    // On save hook_node_insert will be called.
    // That will update the database accordingly.
    node_save($node);
    // Clean up.
    unset($node);
    // Create a frontpage Organisation page.
    // First create a new node object.
    $node = new stdClass();
    // Set the bundle type.
    $node->type = 'page';
    // Set the title.
    $node->title = $organisation;
    // Set the language.
    $node->language = LANGUAGE_NONE;
     // Set the node path.
    $node->path = array('alias' => 'content/organisation');
    // Set some default values.
    node_object_prepare($node);
    // Set the author/owner of the node.
    $node->uid = 1;
    // Let's add standard body field.
    $node->body[$node->language][0]['value'] = $description;
    $node->body[$node->language][0]['summary'] = $description;
    // Define the default plain_text format for the body field.
    $node->body[$node->language][0]['format'] = 'plain_text';
    // Let's add the image field.
    $node->field_image[$node->language][0] = (array) $file;
    // Prepare node for a submit.
    $node = node_submit($node);
    // Add nodesinblock settings to the node.
    $node->nodesinblock_delta = 1;
    $node->nodesinblock_weight = 0;
    $node->nodesinblock_visibility = '*';
    $node->nodesinblock_render = 'teaser:1';
    // Finaly, make sure that the nodesinblock implementation of
    // hook_node_insert() is fired.
    $node->nodesinblock_enable = TRUE;
    // On save hook_insert will be called.
    // That will update the database accordingly.
    node_save($node);
    // Clean up.
    unset($node);
  }

  // Reset the site_frontpage variable to 'frontpage-sitereports'.
  variable_set('site_frontpage', 'frontpage-sitereports');
  // Clear all caches for the view to be available and the title change to take effect.
  drupal_flush_all_caches();
}

/**
 * Implements hook_views_default_views_alter().
 * 
 * Saves the provided slogan into the views display page title so it will show
 * on the homepage instead of the default.
 * 
 * @param type $views
 *   The keyed array of views by reference.
 */
function devtrac_frontpage_sitereports_views_default_views_alter(&$views) {
  if (isset($views['devtrac_frontpage_sitereports'])) {
    // Retrieve the slogan from the variables.
    $slogan = variable_get('devtrac_frontpage_sitereports_slogan', 'Our mission is to show how world aid resources are distributed among supported in underdeveloped regions in the world');
    // Change the title of the views display graphpage title.
    $views['devtrac_frontpage_sitereports']->display['graphpage']->display_options['title'] = $slogan;
  }
}
