<?php
/**
 * @file
 * devtrac7_questionnaire_feature.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function devtrac7_questionnaire_feature_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function devtrac7_questionnaire_feature_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function devtrac7_questionnaire_feature_node_info() {
  $items = array(
    'questionnaire_question' => array(
      'name' => t('Question'),
      'base' => 'node_content',
      'description' => t('This is a Question to be asked in a Questionnaire.'),
      'has_title' => '1',
      'title_label' => t('Question'),
      'help' => '',
    ),
  );
  return $items;
}
