<?php
/**
 * @file devtrac_piwik_configuration.module
 * 
 * Creates configuration form for piwik, which is an alternative to Google 
 * Analytics
 */

/**
 * Implements hook_apps_app_info().
 */
function devtrac_piwik_configuration_apps_app_info() {
  return array(
    'configure form' => 'devtrac_piwik_configuration_app_configure_form',
  );
}

/**
 * Returns a simplified configuration form for the Piwik module.
 */
function devtrac_piwik_configuration_app_configure_form() {
  $form['piwik_info'] = array(
    '#title' => t('Information'),
    '#prefix' => '<div>',
    '#markup' => '<a href="www.piwik.org">Piwik - Web analytics</a> is an open source (GPL license) web analytics software. It gives interesting reports on your website visitors, your popular pages, the search engines keywords they used, the language they speak... and so much more. Piwik aims to be an open source alternative to Google Analytics.<br /><br />Please fill out the general settings. Piwik has many more settings. After enabling the app, you can go to <a href="admin/config/system/piwik">admin/config/system/piwik</a> to change any of these settings.',
    '#suffix' => '</div>',
  );
  $form['piwik_site_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik site ID'),
    '#default_value' => variable_get('piwik_site_id', ''),
    '#required' => TRUE,
    '#description' => t('The user account number is unique to the websites domain. Click the <strong>Settings</strong> link in your Piwik account, then the <strong>Websites</strong> tab and enter the appropriate site <strong>ID</strong> into this field.'),
  );
  $form['piwik_url_http'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik HTTP URL'),
    '#default_value' => variable_get('piwik_url_http', 'http://piwik.mountbatten.net/'),
    '#required' => TRUE,
    '#description' => t('The URL to your Piwik base directory. Example: "http://www.example.com/piwik/".'),
  );
  $form['piwik_url_https'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik HTTPS URL'),
    '#default_value' => variable_get('piwik_url_https', ''),
    '#description' => t('The URL to your Piwik base directory with SSL certificate installed. Required if you track a SSL enabled website. Example: "https://www.example.com/piwik/".'),
  );

  return system_settings_form($form);
}
