<?php 
/**
 * @file
 * Main file for the Devtrac Google Analytics App
 */

/**
 * Implements hook_apps_app_info().
 */
function devtrac_google_analytics_apps_app_info() {
  return array(
    'configure form' => 'devtrac_google_analytics_app_configure_form',
  );
}

/**
 * Returns a simplified configuration form for the Google Analytics module.
 */
function devtrac_google_analytics_app_configure_form() {
  $form['googleanalytics_info'] = array(
    '#title' => t('Information'),
    '#prefix' => '<div>',
    '#markup' => '<a href="www.google.com/analytics">Google Analytics</a> is a free (registration required) website traffic and marketing effectiveness service.<br /><br />Please fill out the general settings. Google Analytics has many more settings. After enabling the app, go to  <a href="admin/config/system/googleanalytics">admin/config/system/googleanalytics</a> to change any of these settings.',
    '#suffix' => '</div>',
  );

  $form['googleanalytics_account'] = array(
    '#type' => 'textfield',
    '#title' => t('Web Property ID'),
    '#default_value' => variable_get('googleanalytics_account', 'UA-'),
    '#required' => TRUE,
    '#description' => t('This ID is unique to each site you want to track separately, and is in the form of UA-xxxxxxx-yy. To get a Web Property ID, <a href="www.google.com/analytics">register your site with Google Analytics</a>, or if you already have registered your site, go to your Google Analytics Settings page to see the ID next to every site profile. <a href="https://developers.google.com/analytics/resources/concepts/gaConceptsAccounts#webProperty">Find more information in the documentation</a>.'),
  );
  return system_settings_form($form);
}
