<?php

/**
 * @file
 */

// Making Devtrac to Devtrac Importer an app.

/**
 * Implements hook_apps_app_info()
 */
function devtrac_to_devtrac_importer_apps_app_info() {
  return array(
    'demo content description' => 'This will load sample data to give an impression of what Devtrac looks like when it is filled up.',
    'demo content module' => 'devtrac_to_devtrac_demodata',
    // This form will be rendered on the app config page:
    'post install callback' => 'devtrac_to_devtrac_importer_app_post_install',
  );
}

function devtrac_to_devtrac_importer_app_post_install() {
  drupal_set_message(t("We are happy to tell you that the Devtrac to Devtrac Importer App is successfully installed."));
}
