<?php
/**
 * @file
 * 
 * Settings for Google analytics
 */

/**
 * Implements hook_apps_app_info()
 */
function google_analytics_apps_app_info() {
  return array(
    'configure form' => 'google_analytics_app_configure_form',
  );
}

/**
 * implements hook_app_configure_form
 */
function google_analytics_app_configure_form() {
  $form['googleanalytics_info'] = array(
    '#title' => t('Information'),
    '#prefix' => '<div>',
    '#markup' => '<a href="www.google.com/analytics">Google Analytics</a> is a free (registration required) website traffic and marketing effectiveness service.<br /><br />Please fill out the general settings. Google Analytics has many more settings. After enabling the app, go to  <a href="admin/config/system/googleanalytics">admin/config/system/googleanalytics</a> to change any of these settings.',
    '#suffix' => '</div>',
  );

  $form['googleanalytics_account'] = array(
    '#type' => 'textfield',
    '#title' => t('Web Property ID'),
    '#default_value' => 'UA-',
    '#required' => TRUE,
    '#description' => t('This ID is unique to each site you want to track separately, and is in the form of UA-xxxxxxx-yy. To get a Web Property ID, <a href="www.google.com/analytics">register your site with Google Analytics</a>, or if you already have registered your site, go to your Google Analytics Settings page to see the ID next to every site profile. <a href="https://developers.google.com/analytics/resources/concepts/gaConceptsAccounts#webProperty">Find more information in the documentation</a>.'),
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => st('Save configurations'),
    '#weight' => 15,
  );
  return $form;
}
/**
 * Implements hook_app_configure_form_submit
 */
function google_analytics_app_configure_form_submit($form, &$form_state) {
  global $install_state;
  $install_state['statistics']['googleanalytics']['googleanalytics_account'] = $form_state['values']['googleanalytics_account'];
  variable_set('googleanalytics_account', $form_state['values']['googleanalytics_account']);
}
